### PR TITLE
Port of linenoise/antirez#104

### PR DESCRIPTION
**Pull request by octplane**
Hello,

This is a simple port of https://github.com/antirez/linenoise/pull/104/files . It adds a method to access the history.

This PR comes in order to be able to use `linenoise-ng` in my FFI binding `rust-linenoise` and preserve:

- the current API in my binding
- the contribution of @sprowell in my binding.

(the PR has also cleaned up some extra space, let me know if you want me to remove these changes from the PR).

### CODE REVIEW

**Comment by ifcologne** [comment]
Thanks for this PR. May I ask you to fill out and sign our [Contributor Agreement](https://www.arangodb.com/documents/cla.pdf) to meet legal requirements? You can scan and email the pdf file to cla@arangodb.com or send it via fax to +49-221-2722999-88. Sorry for the inconvenience, but once the agreement is there we can merge the PR.

**Comment by octplane** [comment]
[0466_001.pdf](https://github.com/arangodb/linenoise-ng/files/137844/0466_001.pdf)

**Comment by jsteemann** [comment]
Thanks!

**Comment by octplane** [comment]
My pleasure!

**Pull request merged**
